export default [
    { "value": "Layout", "title": "放置处" },
    { "value": "views/admin/user/infoOld", "title": "个人资料" },
    { "value": "views/admin/user/index", "title": "用户" },
    { "value": "views/admin/corporation/index", "title": "组织机构" },
    { "value": "views/admin/corporationWork/index", "title": "岗位" },
    { "value": "views/admin/jobPosition/index", "title": "职务" },
    { "value": "views/admin/permission/index", "title": "权限" },
    { "value": "views/admin/permission/module/treeIndex", "title": "模块树" },
    { "value": "views/admin/permission/module/index", "title": "模块" },
    { "value": "views/admin/permission/dataScope/index", "title": "数据权限-行" },
    { "value": "views/admin/permission/dataSchema/index", "title": "数据权限-列" },
    { "value": "views/form/index", "title": "表单设计器" },
    { "value": "views/admin/region/index", "title": "区域" },
    { "value": "views/admin/industryCategory/index", "title": "行业分类" },
    { "value": "views/electricMeter/data/index", "title": "电表数据" },
    { "value": "views/electricMeter/supervise/index", "title": "电表管理" },
    { "value": "views/electricMeter/notes/index", "title": "干预记录" },
]